# fly.toml app configuration file generated for music-trivia-bot on 2026-05-23T15:31:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'music-trivia-bot'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
